
spring:
  application:
    name: safeops-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/safeops}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:secret_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      cookie:
        secure: ${COOKIE_SECURE:true}

security:
  jwt:
    secret: ${JWT_SECRET:L098+jNAes5BMF4oKLeXtpjUOcuGPQozfFDSC2Xdigk=}
    expiration-minutes: 120